name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm test
      
    - name: Build project
      run: npm run build
      
    - name: Deploy (simulated)
      run: npm run deploy
      
    - name: Pipeline completed successfully
      run: |
        echo "🎉 CI/CD Pipeline completed successfully!"
        echo "✅ Code checkout: Completed"
        echo "✅ Dependencies installed: Completed"
        echo "✅ Tests passed: Completed"
        echo "✅ Build completed: Completed"
        echo "✅ Deployment simulated: Completed"
